spring:
  shardingsphere:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_master?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_slave?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_slave1?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      name: mss
      slave-data-source-names: slave0,slave1
    props:
      sql:
        show: true
    enabled: true
  main:
    allow-bean-definition-overriding: true